name = "survey-app"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "survey_db"
database_id = "8a14639b-e945-4833-ac08-02cdbf92c95c"
